pipeline {
    agent any

    environment {
        IMAGE_NAME = 'vishwas1999/practice-script:v1'
    }

    stages {
        stage('Build & Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-creds') {
                        docker.build("${IMAGE_NAME}", "docker-pipeline").push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ Docker image built and pushed successfully!'
        }
        failure {
            echo '❌ Docker build/push failed. Check logs.'
        }
    }
}
